[toolchain]
# The default version of the rustc compiler
# This version is our backend compiler -- self-modified rustc
channel = "rap-rust"
components = ["rustc-dev", "rustc-src", "llvm-tools-preview"]