name: Rap-booting and testing

on:
  push:
    branches: [ "main", "fix-toolchain" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install ninja
      run: |
        pip install ninja
   
    - name: Build RAP 
      run: |
        chmod +x ./install.sh
        ./install.sh
