name: Rap-booting and testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RAP_RECURSIVE: true

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Code Formatting Check
      run: cd rap && cargo fmt --check

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install ninja
      run: |
        pip install ninja
   
    - name: Build RAP 
      run: |
        chmod +x ./install.sh
        ./install.sh

    - name: Check test cases 
      run: cd tests && cargo rap +nightly-2024-06-30 -F -M

    - name: Check rap
      run: cd rap && cargo rap +nightly-2024-06-30 -F -M
