name: Rap-booting and testing

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RAP_RECURSIVE: deep

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Code Formatting Check
      run: cd rap && cargo fmt --check

   
    - name: Build RAP 
      run: ./install.sh

    - name: Check test cases 
      run: cd tests && ./batch.sh -F -M

